### ISSUE TITLE
Possible incorrect routing for Media admin? and other media worker issues

### ISSUE THREAD

**Issue by vincejv** [tcpipuk/tcpipuk.github.io#17]
The following nginx directive will break `_synapse/admin/v1/users/<user_id>/override_ratelimit` for `synapse.app.media_repository` worker types
```sh
# Media admin
location ~ ^/_synapse/admin/v1/(purge_)?(media(_cache)?|room|user|quarantine_media|users)/.*|media$ {
  include private.conf;
  set $proxy_pass http://synapse_inbound_media;
  include proxy.conf;
}
```

and also `synapse.app.media_repository` worker should have `media` declared in worker_listners > resources for the media routes to work, this is not specified in the docs, only states `client` and `federation`
```yaml
 - path: '/var/run/synapse/media-1.sock'
    type: http
    x_forwarded: true
    resources:
      - names: [media]
```
